#!/bin/sh

. /etc/naturfakta-web.conf

if [ "$#" -ne 1 -o "$1" = "" ] ; then
  echo "Missing arguments"
  echo "Usage $0 <inputfile.sql>"
  exit 1
fi

echo "Importing..."
mysql -u $DBUSER -p${DBPASS} $DBNAME < $1
