#!/bin/sh

. /etc/addrnodeimport.conf

if [ "$#" -ne 1 -o "$1" = "" ] ; then
  echo "Missing arguments"
  echo "Usage $0 <outputfile.sql>"
  exit 1
fi

echo "Backing up to $1..."
mysqldump -u $DBUSER -p${DBPASS} --extended-insert=FALSE $DBNAME municipalities osmimportresp update_requests > $1
