#!/bin/sh

set -e

. /usr/share/debconf/confmodule

db_input high addrnodeimport/db-name || true
db_input high addrnodeimport/db-user || true
db_input high addrnodeimport/db-password || true
db_input high addrnodeimport/root-password || true
db_input high addrnodeimport/enable || true
db_go

exit 0
