#!/bin/sh


./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1001
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1002
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1003
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1004
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1014
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1017
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1018
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1021
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1026
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1027
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1029
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1032
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1034
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1037
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1046
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1101
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1102
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1111
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1112
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1114
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1119
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1120
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1121
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1122
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1129
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1130
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1133
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1134
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1135
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1201
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1235
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1241
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1242
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1243
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1244
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1245
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1246
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1247
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1251
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1252
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1253
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1256
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1259
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1260
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1263
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1264
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1265
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1266
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1563
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1566
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1567
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1571
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1573
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1576
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1601
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1612
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1613
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1617
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1620
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1621
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1622
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1624
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1627
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1630
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1632
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1634
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1635
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1636
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1638
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1640
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1644
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1648
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1653
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1657
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1662
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1663
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1664
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1665
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1711
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1714
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1717
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1718
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1719
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1724
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1756
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1805
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1851
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1852
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1853
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1854
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1866
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1867
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1868
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1870
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1871
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1902
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1903
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1911
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1913
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1917
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1919
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1920
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1922
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1923
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1924
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1925
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1926
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1927
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1928
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1929
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1931
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1933
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1936
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1938
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1939
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1940
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1941
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1942
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1943
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 2002
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 2003
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 2004
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 2011
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 2012
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 2014
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 2015
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 2017
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 2018
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 2019
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 2020
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 2021
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 2022
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 2023
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 2024
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 2025
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 2027
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 2028
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 2030
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 436
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 437
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 439
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 441
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 633
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 826
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 831
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 833
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 834
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 919
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 928
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 929
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 935
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 937
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 938
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 940
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 941
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 101
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 104
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 105
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 106
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 111
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 118
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 119
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 121
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 122
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 123
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 124
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 125
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 127
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 128
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 135
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 136
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 137
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 138
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 211
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 213
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 214
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 215
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 216
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 217
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 219
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 220
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 221
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 226
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 227
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 228
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 229
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 230
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 231
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 233
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 234
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 235
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 238
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 301
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 533
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 602
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 625
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 626
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 627
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 628
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 701
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 702
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 704
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 706
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 711
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 713
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 714
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 716
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 719
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 720
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 722
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 723
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1103
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1106
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1124
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1127
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1141
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1142
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1144
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1145
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1146
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1149
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1160
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1401
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1411
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1412
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1413
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1416
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1417
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1418
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1419
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1420
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1421
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1422
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1424
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1426
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1428
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1429
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1430
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1431
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1432
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1433
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1438
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1439
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1441
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1443
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1444
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1445
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1449
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1502
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1504
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1505
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1511
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1514
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1515
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1516
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1517
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1519
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1520
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1523
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1524
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1525
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1526
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1528
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1529
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1531
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1532
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1534
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1535
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1539
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1543
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1545
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1546
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1547
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1548
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1551
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1554
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1557
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1560
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1576
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 512
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 513
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1633
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1702
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1703
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1721
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1725
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1736
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1738
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1739
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1740
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1742
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1743
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1744
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1748
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1749
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1750
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1751
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1755
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1804
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1811
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1812
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1813
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1815
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1816
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1818
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1820
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1822
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1824
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1825
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1826
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1827
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1828
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1832
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1833
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1834
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1835
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1836
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1837
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1838
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1839
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1840
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1841
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1845
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1848
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1849
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1850
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1856
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1857
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1859
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1860
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1865
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1874
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1151
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1211
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1216
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1219
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1221
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1222
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1223
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1224
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1227
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1228
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1231
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1232
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1233
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1234
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 1238
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 236
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 237
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 238
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 239
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 402
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 403
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 412
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 415
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 417
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 418
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 419
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 423
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 425
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 426
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 427
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 428
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 429
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 430
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 432
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 434
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 501
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 502
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 511
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 514
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 515
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 516
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 517
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 519
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 520
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 521
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 522
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 528
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 529
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 534
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 536
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 538
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 540
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 541
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 542
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 543
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 544
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 545
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 604
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 605
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 612
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 615
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 616
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 617
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 618
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 619
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 620
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 621
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 622
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 623
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 624
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 625
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 631
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 632
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 633
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 805
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 806
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 811
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 814
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 815
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 817
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 819
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 821
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 822
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 826
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 827
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 828
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 829
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 830
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 901
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 904
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 906
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 911
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 912
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 914
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 919
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 926
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 532
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 420
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 709
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 807
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 438
./addrnodeimport.py /home/ruben/Vegdata_Norge_UTM33_Geometri_SOSI.zip 728

