#!/bin/sh


rm -rf /var/cache/addrnodeimport/norway-latest.osm.pbf
rm -rf /tmp/osm_temp/ways.pbf /tmp/osm_temp/nodes.pbf
wget http://download.geofabrik.de/europe/norway-latest.osm.pbf -O /var/cache/addrnodeimport/norway-latest.osm.pbf

/usr/lib/addrnodeimport/python/doall.py  1001
/usr/lib/addrnodeimport/python/doall.py  1002
/usr/lib/addrnodeimport/python/doall.py  1003
/usr/lib/addrnodeimport/python/doall.py  1004
/usr/lib/addrnodeimport/python/doall.py  1014
/usr/lib/addrnodeimport/python/doall.py  1017
/usr/lib/addrnodeimport/python/doall.py  1018
/usr/lib/addrnodeimport/python/doall.py  1021
/usr/lib/addrnodeimport/python/doall.py  1026
/usr/lib/addrnodeimport/python/doall.py  1027
/usr/lib/addrnodeimport/python/doall.py  1029
/usr/lib/addrnodeimport/python/doall.py  1032
/usr/lib/addrnodeimport/python/doall.py  1034
/usr/lib/addrnodeimport/python/doall.py  1037
/usr/lib/addrnodeimport/python/doall.py  1046
/usr/lib/addrnodeimport/python/doall.py  1101
/usr/lib/addrnodeimport/python/doall.py  1102
/usr/lib/addrnodeimport/python/doall.py  1111
/usr/lib/addrnodeimport/python/doall.py  1112
/usr/lib/addrnodeimport/python/doall.py  1114
/usr/lib/addrnodeimport/python/doall.py  1119
/usr/lib/addrnodeimport/python/doall.py  1120
/usr/lib/addrnodeimport/python/doall.py  1121
/usr/lib/addrnodeimport/python/doall.py  1122
/usr/lib/addrnodeimport/python/doall.py  1129
/usr/lib/addrnodeimport/python/doall.py  1130
/usr/lib/addrnodeimport/python/doall.py  1133
/usr/lib/addrnodeimport/python/doall.py  1134
/usr/lib/addrnodeimport/python/doall.py  1135
/usr/lib/addrnodeimport/python/doall.py  1201
/usr/lib/addrnodeimport/python/doall.py  1235
/usr/lib/addrnodeimport/python/doall.py  1241
/usr/lib/addrnodeimport/python/doall.py  1242
/usr/lib/addrnodeimport/python/doall.py  1243
/usr/lib/addrnodeimport/python/doall.py  1244
/usr/lib/addrnodeimport/python/doall.py  1245
/usr/lib/addrnodeimport/python/doall.py  1246
/usr/lib/addrnodeimport/python/doall.py  1247
/usr/lib/addrnodeimport/python/doall.py  1251
/usr/lib/addrnodeimport/python/doall.py  1252
/usr/lib/addrnodeimport/python/doall.py  1253
/usr/lib/addrnodeimport/python/doall.py  1256
/usr/lib/addrnodeimport/python/doall.py  1259
/usr/lib/addrnodeimport/python/doall.py  1260
/usr/lib/addrnodeimport/python/doall.py  1263
/usr/lib/addrnodeimport/python/doall.py  1264
/usr/lib/addrnodeimport/python/doall.py  1265
/usr/lib/addrnodeimport/python/doall.py  1266
/usr/lib/addrnodeimport/python/doall.py  1563
/usr/lib/addrnodeimport/python/doall.py  1566
/usr/lib/addrnodeimport/python/doall.py  1567
/usr/lib/addrnodeimport/python/doall.py  1571
/usr/lib/addrnodeimport/python/doall.py  1573
/usr/lib/addrnodeimport/python/doall.py  1576
/usr/lib/addrnodeimport/python/doall.py  1601
/usr/lib/addrnodeimport/python/doall.py  1612
/usr/lib/addrnodeimport/python/doall.py  1613
/usr/lib/addrnodeimport/python/doall.py  1617
/usr/lib/addrnodeimport/python/doall.py  1620
/usr/lib/addrnodeimport/python/doall.py  1621
/usr/lib/addrnodeimport/python/doall.py  1622
/usr/lib/addrnodeimport/python/doall.py  1624
/usr/lib/addrnodeimport/python/doall.py  1627
/usr/lib/addrnodeimport/python/doall.py  1630
/usr/lib/addrnodeimport/python/doall.py  1632
/usr/lib/addrnodeimport/python/doall.py  1634
/usr/lib/addrnodeimport/python/doall.py  1635
/usr/lib/addrnodeimport/python/doall.py  1636
/usr/lib/addrnodeimport/python/doall.py  1638
/usr/lib/addrnodeimport/python/doall.py  1640
/usr/lib/addrnodeimport/python/doall.py  1644
/usr/lib/addrnodeimport/python/doall.py  1648
/usr/lib/addrnodeimport/python/doall.py  1653
/usr/lib/addrnodeimport/python/doall.py  1657
/usr/lib/addrnodeimport/python/doall.py  1662
/usr/lib/addrnodeimport/python/doall.py  1663
/usr/lib/addrnodeimport/python/doall.py  1664
/usr/lib/addrnodeimport/python/doall.py  1665
/usr/lib/addrnodeimport/python/doall.py  1711
/usr/lib/addrnodeimport/python/doall.py  1714
/usr/lib/addrnodeimport/python/doall.py  1717
/usr/lib/addrnodeimport/python/doall.py  1718
/usr/lib/addrnodeimport/python/doall.py  1719
/usr/lib/addrnodeimport/python/doall.py  1724
/usr/lib/addrnodeimport/python/doall.py  1756
/usr/lib/addrnodeimport/python/doall.py  1805
/usr/lib/addrnodeimport/python/doall.py  1851
/usr/lib/addrnodeimport/python/doall.py  1852
/usr/lib/addrnodeimport/python/doall.py  1853
/usr/lib/addrnodeimport/python/doall.py  1854
/usr/lib/addrnodeimport/python/doall.py  1866
/usr/lib/addrnodeimport/python/doall.py  1867
/usr/lib/addrnodeimport/python/doall.py  1868
/usr/lib/addrnodeimport/python/doall.py  1870
/usr/lib/addrnodeimport/python/doall.py  1871
/usr/lib/addrnodeimport/python/doall.py  1902
/usr/lib/addrnodeimport/python/doall.py  1903
/usr/lib/addrnodeimport/python/doall.py  1911
/usr/lib/addrnodeimport/python/doall.py  1913
/usr/lib/addrnodeimport/python/doall.py  1917
/usr/lib/addrnodeimport/python/doall.py  1919
/usr/lib/addrnodeimport/python/doall.py  1920
/usr/lib/addrnodeimport/python/doall.py  1922
/usr/lib/addrnodeimport/python/doall.py  1923
/usr/lib/addrnodeimport/python/doall.py  1924
/usr/lib/addrnodeimport/python/doall.py  1925
/usr/lib/addrnodeimport/python/doall.py  1926
/usr/lib/addrnodeimport/python/doall.py  1927
/usr/lib/addrnodeimport/python/doall.py  1928
/usr/lib/addrnodeimport/python/doall.py  1929
/usr/lib/addrnodeimport/python/doall.py  1931
/usr/lib/addrnodeimport/python/doall.py  1933
/usr/lib/addrnodeimport/python/doall.py  1936
/usr/lib/addrnodeimport/python/doall.py  1938
/usr/lib/addrnodeimport/python/doall.py  1939
/usr/lib/addrnodeimport/python/doall.py  1940
/usr/lib/addrnodeimport/python/doall.py  1941
/usr/lib/addrnodeimport/python/doall.py  1942
/usr/lib/addrnodeimport/python/doall.py  1943
/usr/lib/addrnodeimport/python/doall.py  2002
/usr/lib/addrnodeimport/python/doall.py  2003
/usr/lib/addrnodeimport/python/doall.py  2004
/usr/lib/addrnodeimport/python/doall.py  2011
/usr/lib/addrnodeimport/python/doall.py  2012
/usr/lib/addrnodeimport/python/doall.py  2014
/usr/lib/addrnodeimport/python/doall.py  2015
/usr/lib/addrnodeimport/python/doall.py  2017
/usr/lib/addrnodeimport/python/doall.py  2018
/usr/lib/addrnodeimport/python/doall.py  2019
/usr/lib/addrnodeimport/python/doall.py  2020
/usr/lib/addrnodeimport/python/doall.py  2021
/usr/lib/addrnodeimport/python/doall.py  2022
/usr/lib/addrnodeimport/python/doall.py  2023
/usr/lib/addrnodeimport/python/doall.py  2024
/usr/lib/addrnodeimport/python/doall.py  2025
/usr/lib/addrnodeimport/python/doall.py  2027
/usr/lib/addrnodeimport/python/doall.py  2028
/usr/lib/addrnodeimport/python/doall.py  2030
/usr/lib/addrnodeimport/python/doall.py  436
/usr/lib/addrnodeimport/python/doall.py  437
/usr/lib/addrnodeimport/python/doall.py  439
/usr/lib/addrnodeimport/python/doall.py  441
/usr/lib/addrnodeimport/python/doall.py  633
/usr/lib/addrnodeimport/python/doall.py  826
/usr/lib/addrnodeimport/python/doall.py  831
/usr/lib/addrnodeimport/python/doall.py  833
/usr/lib/addrnodeimport/python/doall.py  834
/usr/lib/addrnodeimport/python/doall.py  919
/usr/lib/addrnodeimport/python/doall.py  928
/usr/lib/addrnodeimport/python/doall.py  929
/usr/lib/addrnodeimport/python/doall.py  935
/usr/lib/addrnodeimport/python/doall.py  937
/usr/lib/addrnodeimport/python/doall.py  938
/usr/lib/addrnodeimport/python/doall.py  940
/usr/lib/addrnodeimport/python/doall.py  941
/usr/lib/addrnodeimport/python/doall.py  101
/usr/lib/addrnodeimport/python/doall.py  104
/usr/lib/addrnodeimport/python/doall.py  105
/usr/lib/addrnodeimport/python/doall.py  106
/usr/lib/addrnodeimport/python/doall.py  111
/usr/lib/addrnodeimport/python/doall.py  118
/usr/lib/addrnodeimport/python/doall.py  119
/usr/lib/addrnodeimport/python/doall.py  121
/usr/lib/addrnodeimport/python/doall.py  122
/usr/lib/addrnodeimport/python/doall.py  123
/usr/lib/addrnodeimport/python/doall.py  124
/usr/lib/addrnodeimport/python/doall.py  125
/usr/lib/addrnodeimport/python/doall.py  127
/usr/lib/addrnodeimport/python/doall.py  128
/usr/lib/addrnodeimport/python/doall.py  135
/usr/lib/addrnodeimport/python/doall.py  136
/usr/lib/addrnodeimport/python/doall.py  137
/usr/lib/addrnodeimport/python/doall.py  138
/usr/lib/addrnodeimport/python/doall.py  211
/usr/lib/addrnodeimport/python/doall.py  213
/usr/lib/addrnodeimport/python/doall.py  214
/usr/lib/addrnodeimport/python/doall.py  215
/usr/lib/addrnodeimport/python/doall.py  216
/usr/lib/addrnodeimport/python/doall.py  217
/usr/lib/addrnodeimport/python/doall.py  219
/usr/lib/addrnodeimport/python/doall.py  220
/usr/lib/addrnodeimport/python/doall.py  221
/usr/lib/addrnodeimport/python/doall.py  226
/usr/lib/addrnodeimport/python/doall.py  227
/usr/lib/addrnodeimport/python/doall.py  228
/usr/lib/addrnodeimport/python/doall.py  229
/usr/lib/addrnodeimport/python/doall.py  230
/usr/lib/addrnodeimport/python/doall.py  231
/usr/lib/addrnodeimport/python/doall.py  233
/usr/lib/addrnodeimport/python/doall.py  234
/usr/lib/addrnodeimport/python/doall.py  235
/usr/lib/addrnodeimport/python/doall.py  238
/usr/lib/addrnodeimport/python/doall.py  301
/usr/lib/addrnodeimport/python/doall.py  533
/usr/lib/addrnodeimport/python/doall.py  602
/usr/lib/addrnodeimport/python/doall.py  625
/usr/lib/addrnodeimport/python/doall.py  626
/usr/lib/addrnodeimport/python/doall.py  627
/usr/lib/addrnodeimport/python/doall.py  628
/usr/lib/addrnodeimport/python/doall.py  701
/usr/lib/addrnodeimport/python/doall.py  702
/usr/lib/addrnodeimport/python/doall.py  704
/usr/lib/addrnodeimport/python/doall.py  710
/usr/lib/addrnodeimport/python/doall.py  711
/usr/lib/addrnodeimport/python/doall.py  713
/usr/lib/addrnodeimport/python/doall.py  714
/usr/lib/addrnodeimport/python/doall.py  716
/usr/lib/addrnodeimport/python/doall.py  722
/usr/lib/addrnodeimport/python/doall.py  723
/usr/lib/addrnodeimport/python/doall.py  1103
/usr/lib/addrnodeimport/python/doall.py  1106
/usr/lib/addrnodeimport/python/doall.py  1124
/usr/lib/addrnodeimport/python/doall.py  1127
/usr/lib/addrnodeimport/python/doall.py  1141
/usr/lib/addrnodeimport/python/doall.py  1142
/usr/lib/addrnodeimport/python/doall.py  1144
/usr/lib/addrnodeimport/python/doall.py  1145
/usr/lib/addrnodeimport/python/doall.py  1146
/usr/lib/addrnodeimport/python/doall.py  1149
/usr/lib/addrnodeimport/python/doall.py  1160
/usr/lib/addrnodeimport/python/doall.py  1401
/usr/lib/addrnodeimport/python/doall.py  1411
/usr/lib/addrnodeimport/python/doall.py  1412
/usr/lib/addrnodeimport/python/doall.py  1413
/usr/lib/addrnodeimport/python/doall.py  1416
/usr/lib/addrnodeimport/python/doall.py  1417
/usr/lib/addrnodeimport/python/doall.py  1418
/usr/lib/addrnodeimport/python/doall.py  1419
/usr/lib/addrnodeimport/python/doall.py  1420
/usr/lib/addrnodeimport/python/doall.py  1421
/usr/lib/addrnodeimport/python/doall.py  1422
/usr/lib/addrnodeimport/python/doall.py  1424
/usr/lib/addrnodeimport/python/doall.py  1426
/usr/lib/addrnodeimport/python/doall.py  1428
/usr/lib/addrnodeimport/python/doall.py  1429
/usr/lib/addrnodeimport/python/doall.py  1430
/usr/lib/addrnodeimport/python/doall.py  1431
/usr/lib/addrnodeimport/python/doall.py  1432
/usr/lib/addrnodeimport/python/doall.py  1433
/usr/lib/addrnodeimport/python/doall.py  1438
/usr/lib/addrnodeimport/python/doall.py  1439
/usr/lib/addrnodeimport/python/doall.py  1441
/usr/lib/addrnodeimport/python/doall.py  1443
/usr/lib/addrnodeimport/python/doall.py  1444
/usr/lib/addrnodeimport/python/doall.py  1445
/usr/lib/addrnodeimport/python/doall.py  1449
/usr/lib/addrnodeimport/python/doall.py  1502
/usr/lib/addrnodeimport/python/doall.py  1504
/usr/lib/addrnodeimport/python/doall.py  1505
/usr/lib/addrnodeimport/python/doall.py  1511
/usr/lib/addrnodeimport/python/doall.py  1514
/usr/lib/addrnodeimport/python/doall.py  1515
/usr/lib/addrnodeimport/python/doall.py  1516
/usr/lib/addrnodeimport/python/doall.py  1517
/usr/lib/addrnodeimport/python/doall.py  1519
/usr/lib/addrnodeimport/python/doall.py  1520
/usr/lib/addrnodeimport/python/doall.py  1523
/usr/lib/addrnodeimport/python/doall.py  1524
/usr/lib/addrnodeimport/python/doall.py  1525
/usr/lib/addrnodeimport/python/doall.py  1526
/usr/lib/addrnodeimport/python/doall.py  1528
/usr/lib/addrnodeimport/python/doall.py  1529
/usr/lib/addrnodeimport/python/doall.py  1531
/usr/lib/addrnodeimport/python/doall.py  1532
/usr/lib/addrnodeimport/python/doall.py  1534
/usr/lib/addrnodeimport/python/doall.py  1535
/usr/lib/addrnodeimport/python/doall.py  1539
/usr/lib/addrnodeimport/python/doall.py  1543
/usr/lib/addrnodeimport/python/doall.py  1545
/usr/lib/addrnodeimport/python/doall.py  1546
/usr/lib/addrnodeimport/python/doall.py  1547
/usr/lib/addrnodeimport/python/doall.py  1548
/usr/lib/addrnodeimport/python/doall.py  1551
/usr/lib/addrnodeimport/python/doall.py  1554
/usr/lib/addrnodeimport/python/doall.py  1557
/usr/lib/addrnodeimport/python/doall.py  1560
/usr/lib/addrnodeimport/python/doall.py  1576
/usr/lib/addrnodeimport/python/doall.py  512
/usr/lib/addrnodeimport/python/doall.py  513
/usr/lib/addrnodeimport/python/doall.py  1633
/usr/lib/addrnodeimport/python/doall.py  1702
/usr/lib/addrnodeimport/python/doall.py  1703
/usr/lib/addrnodeimport/python/doall.py  1721
/usr/lib/addrnodeimport/python/doall.py  1725
/usr/lib/addrnodeimport/python/doall.py  1736
/usr/lib/addrnodeimport/python/doall.py  1738
/usr/lib/addrnodeimport/python/doall.py  1739
/usr/lib/addrnodeimport/python/doall.py  1740
/usr/lib/addrnodeimport/python/doall.py  1742
/usr/lib/addrnodeimport/python/doall.py  1743
/usr/lib/addrnodeimport/python/doall.py  1744
/usr/lib/addrnodeimport/python/doall.py  1748
/usr/lib/addrnodeimport/python/doall.py  1749
/usr/lib/addrnodeimport/python/doall.py  1750
/usr/lib/addrnodeimport/python/doall.py  1751
/usr/lib/addrnodeimport/python/doall.py  1755
/usr/lib/addrnodeimport/python/doall.py  1804
/usr/lib/addrnodeimport/python/doall.py  1811
/usr/lib/addrnodeimport/python/doall.py  1812
/usr/lib/addrnodeimport/python/doall.py  1813
/usr/lib/addrnodeimport/python/doall.py  1815
/usr/lib/addrnodeimport/python/doall.py  1816
/usr/lib/addrnodeimport/python/doall.py  1818
/usr/lib/addrnodeimport/python/doall.py  1820
/usr/lib/addrnodeimport/python/doall.py  1822
/usr/lib/addrnodeimport/python/doall.py  1824
/usr/lib/addrnodeimport/python/doall.py  1825
/usr/lib/addrnodeimport/python/doall.py  1826
/usr/lib/addrnodeimport/python/doall.py  1827
/usr/lib/addrnodeimport/python/doall.py  1828
/usr/lib/addrnodeimport/python/doall.py  1832
/usr/lib/addrnodeimport/python/doall.py  1833
/usr/lib/addrnodeimport/python/doall.py  1834
/usr/lib/addrnodeimport/python/doall.py  1835
/usr/lib/addrnodeimport/python/doall.py  1836
/usr/lib/addrnodeimport/python/doall.py  1837
/usr/lib/addrnodeimport/python/doall.py  1838
/usr/lib/addrnodeimport/python/doall.py  1839
/usr/lib/addrnodeimport/python/doall.py  1840
/usr/lib/addrnodeimport/python/doall.py  1841
/usr/lib/addrnodeimport/python/doall.py  1845
/usr/lib/addrnodeimport/python/doall.py  1848
/usr/lib/addrnodeimport/python/doall.py  1849
/usr/lib/addrnodeimport/python/doall.py  1850
/usr/lib/addrnodeimport/python/doall.py  1856
/usr/lib/addrnodeimport/python/doall.py  1857
/usr/lib/addrnodeimport/python/doall.py  1859
/usr/lib/addrnodeimport/python/doall.py  1860
/usr/lib/addrnodeimport/python/doall.py  1865
/usr/lib/addrnodeimport/python/doall.py  1874
/usr/lib/addrnodeimport/python/doall.py  1151
/usr/lib/addrnodeimport/python/doall.py  1211
/usr/lib/addrnodeimport/python/doall.py  1216
/usr/lib/addrnodeimport/python/doall.py  1219
/usr/lib/addrnodeimport/python/doall.py  1221
/usr/lib/addrnodeimport/python/doall.py  1222
/usr/lib/addrnodeimport/python/doall.py  1223
/usr/lib/addrnodeimport/python/doall.py  1224
/usr/lib/addrnodeimport/python/doall.py  1227
/usr/lib/addrnodeimport/python/doall.py  1228
/usr/lib/addrnodeimport/python/doall.py  1231
/usr/lib/addrnodeimport/python/doall.py  1232
/usr/lib/addrnodeimport/python/doall.py  1233
/usr/lib/addrnodeimport/python/doall.py  1234
/usr/lib/addrnodeimport/python/doall.py  1238
/usr/lib/addrnodeimport/python/doall.py  236
/usr/lib/addrnodeimport/python/doall.py  237
/usr/lib/addrnodeimport/python/doall.py  238
/usr/lib/addrnodeimport/python/doall.py  239
/usr/lib/addrnodeimport/python/doall.py  402
/usr/lib/addrnodeimport/python/doall.py  403
/usr/lib/addrnodeimport/python/doall.py  412
/usr/lib/addrnodeimport/python/doall.py  415
/usr/lib/addrnodeimport/python/doall.py  417
/usr/lib/addrnodeimport/python/doall.py  418
/usr/lib/addrnodeimport/python/doall.py  419
/usr/lib/addrnodeimport/python/doall.py  423
/usr/lib/addrnodeimport/python/doall.py  425
/usr/lib/addrnodeimport/python/doall.py  426
/usr/lib/addrnodeimport/python/doall.py  427
/usr/lib/addrnodeimport/python/doall.py  428
/usr/lib/addrnodeimport/python/doall.py  429
/usr/lib/addrnodeimport/python/doall.py  430
/usr/lib/addrnodeimport/python/doall.py  432
/usr/lib/addrnodeimport/python/doall.py  434
/usr/lib/addrnodeimport/python/doall.py  501
/usr/lib/addrnodeimport/python/doall.py  502
/usr/lib/addrnodeimport/python/doall.py  511
/usr/lib/addrnodeimport/python/doall.py  514
/usr/lib/addrnodeimport/python/doall.py  515
/usr/lib/addrnodeimport/python/doall.py  516
/usr/lib/addrnodeimport/python/doall.py  517
/usr/lib/addrnodeimport/python/doall.py  519
/usr/lib/addrnodeimport/python/doall.py  520
/usr/lib/addrnodeimport/python/doall.py  521
/usr/lib/addrnodeimport/python/doall.py  522
/usr/lib/addrnodeimport/python/doall.py  528
/usr/lib/addrnodeimport/python/doall.py  529
/usr/lib/addrnodeimport/python/doall.py  534
/usr/lib/addrnodeimport/python/doall.py  536
/usr/lib/addrnodeimport/python/doall.py  538
/usr/lib/addrnodeimport/python/doall.py  540
/usr/lib/addrnodeimport/python/doall.py  541
/usr/lib/addrnodeimport/python/doall.py  542
/usr/lib/addrnodeimport/python/doall.py  543
/usr/lib/addrnodeimport/python/doall.py  544
/usr/lib/addrnodeimport/python/doall.py  545
/usr/lib/addrnodeimport/python/doall.py  604
/usr/lib/addrnodeimport/python/doall.py  605
/usr/lib/addrnodeimport/python/doall.py  612
/usr/lib/addrnodeimport/python/doall.py  615
/usr/lib/addrnodeimport/python/doall.py  616
/usr/lib/addrnodeimport/python/doall.py  617
/usr/lib/addrnodeimport/python/doall.py  618
/usr/lib/addrnodeimport/python/doall.py  619
/usr/lib/addrnodeimport/python/doall.py  620
/usr/lib/addrnodeimport/python/doall.py  621
/usr/lib/addrnodeimport/python/doall.py  622
/usr/lib/addrnodeimport/python/doall.py  623
/usr/lib/addrnodeimport/python/doall.py  624
/usr/lib/addrnodeimport/python/doall.py  625
/usr/lib/addrnodeimport/python/doall.py  631
/usr/lib/addrnodeimport/python/doall.py  632
/usr/lib/addrnodeimport/python/doall.py  633
/usr/lib/addrnodeimport/python/doall.py  805
/usr/lib/addrnodeimport/python/doall.py  806
/usr/lib/addrnodeimport/python/doall.py  811
/usr/lib/addrnodeimport/python/doall.py  814
/usr/lib/addrnodeimport/python/doall.py  815
/usr/lib/addrnodeimport/python/doall.py  817
/usr/lib/addrnodeimport/python/doall.py  819
/usr/lib/addrnodeimport/python/doall.py  821
/usr/lib/addrnodeimport/python/doall.py  822
/usr/lib/addrnodeimport/python/doall.py  826
/usr/lib/addrnodeimport/python/doall.py  827
/usr/lib/addrnodeimport/python/doall.py  828
/usr/lib/addrnodeimport/python/doall.py  829
/usr/lib/addrnodeimport/python/doall.py  830
/usr/lib/addrnodeimport/python/doall.py  901
/usr/lib/addrnodeimport/python/doall.py  904
/usr/lib/addrnodeimport/python/doall.py  906
/usr/lib/addrnodeimport/python/doall.py  911
/usr/lib/addrnodeimport/python/doall.py  912
/usr/lib/addrnodeimport/python/doall.py  914
/usr/lib/addrnodeimport/python/doall.py  919
/usr/lib/addrnodeimport/python/doall.py  926
/usr/lib/addrnodeimport/python/doall.py  532
/usr/lib/addrnodeimport/python/doall.py  420
/usr/lib/addrnodeimport/python/doall.py  709
/usr/lib/addrnodeimport/python/doall.py  807
/usr/lib/addrnodeimport/python/doall.py  438
/usr/lib/addrnodeimport/python/doall.py  728

